seed_everything: 42

model:
  class_path: model.Yolo
  init_args:
    model: l
    num_classes: 2
    loss_ratio: 0.0265
    time_window: 8
    iou_threshold: 0.45
    learning_rate: 0.001
    clip_grad: 1
    dt: 0.002
    init_weights: true
    sizes: [[20, 40], [80, 140], [220, 300]]
    aspect_ratios:
      [[0.5, 1.0, 2.0, 5.0], [0.5, 1.0, 2.0, 5.0], [0.5, 1.0, 2.0, 5.0]]
    load_model: "yolo8l_gen1"
    plotter:
      class_path: utils.Plotter
      init_args:
        threshold: 0.0
        show_video: true
        save_video: false
        file_path: log
        file_name: out

data:
  class_path: utils.PropheseeDataModule
  init_args:
    root: ../snn_for_object_detection/data
    dataset: gen1
    batch_size: 8
    num_workers: 4
    num_steps: 42
    time_step_us: 8000
    resize: [256, 320]

trainer:
  accelerator: gpu
  strategy: auto
  devices: -1
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: map_50
        save_top_k: 3
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 3
  deterministic: true
  val_check_interval: 500
  limit_val_batches: 100
  # limit_test_batches: 10
  log_every_n_steps: 20
  enable_checkpointing: true
